export interface Hexagram {
  id: number;
  name: string;
  pinyin: string;
  meaning: string;
  shortDesc: string;
  binary: string; // Bottom to top: 1 for yang (-), 0 for yin (- -)
}

export const HEXAGRAMS: Hexagram[] = [
  { id: 1, name: "乾", pinyin: "Qián", meaning: "The Creative", shortDesc: "Infinite power, leadership, and heaven's vitality.", binary: "111111" },
  { id: 2, name: "坤", pinyin: "Kūn", meaning: "The Receptive", shortDesc: "Nurturing earth, devotion, and yielding strength.", binary: "000000" },
  { id: 3, name: "屯", pinyin: "Zhūn", meaning: "Difficulty at the Beginning", shortDesc: "Sprouting seeds, initial struggles, and perseverance.", binary: "100010" },
  { id: 4, name: "蒙", pinyin: "Méng", meaning: "Youthful Folly", shortDesc: "Hidden potential, learning, and the path of the student.", binary: "010001" },
  { id: 5, name: "需", pinyin: "Xū", meaning: "Waiting", shortDesc: "Patience, nourishment, and waiting for the right moment.", binary: "111010" },
  { id: 6, name: "讼", pinyin: "Sòng", meaning: "Conflict", shortDesc: "Dispute, cautious progress, and seeking mediation.", binary: "010111" },
  { id: 7, name: "师", pinyin: "Shī", meaning: "The Army", shortDesc: "Discipline, collective strength, and strategic leadership.", binary: "010000" },
  { id: 8, name: "比", pinyin: "Bǐ", meaning: "Holding Together", shortDesc: "Unity, friendship, and finding your tribe.", binary: "000001" },
  { id: 9, name: "小畜", pinyin: "Xiǎo Xù", meaning: "Small Taming", shortDesc: "Gentle persuasion, small accumulations, and patience.", binary: "110111" },
  { id: 10, name: "履", pinyin: "Lǚ", meaning: "Treading", shortDesc: "Walking with caution, conduct, and following the path.", binary: "111011" },
  { id: 11, name: "泰", pinyin: "Tài", meaning: "Peace", shortDesc: "Harmony, prosperity, and the meeting of heaven and earth.", binary: "111000" },
  { id: 12, name: "否", pinyin: "Pǐ", meaning: "Standstill", shortDesc: "Obstruction, separation, and internal focus.", binary: "000111" },
  { id: 13, name: "同人", pinyin: "Tóng Rén", meaning: "Fellowship", shortDesc: "Universal brotherhood, shared goals, and community.", binary: "101111" },
  { id: 14, name: "大有", pinyin: "Dà Yǒu", meaning: "Great Possession", shortDesc: "Abundance, supreme success, and enlightened power.", binary: "111101" },
  { id: 15, name: "谦", pinyin: "Qiān", meaning: "Modesty", shortDesc: "Humility, leveling the high, and enduring honor.", binary: "001000" },
  { id: 16, name: "豫", pinyin: "Yù", meaning: "Enthusiasm", shortDesc: "Joy, movement, and preparation for great deeds.", binary: "000100" },
  { id: 17, name: "随", pinyin: "Suí", meaning: "Following", shortDesc: "Adaptability, following truth, and finding rest.", binary: "100110" },
  { id: 18, name: "蛊", pinyin: "Gǔ", meaning: "Work on the Decayed", shortDesc: "Repairing the past, renewal, and active healing.", binary: "011001" },
  { id: 19, name: "临", pinyin: "Lín", meaning: "Approach", shortDesc: "Arrival of greatness, supervision, and early spring.", binary: "110000" },
  { id: 20, name: "观", pinyin: "Guān", meaning: "Contemplation", shortDesc: "Deep observation, perspective, and setting an example.", binary: "000011" },
  { id: 21, name: "噬嗑", pinyin: "Shì Kè", meaning: "Biting Through", shortDesc: "Decisive action, justice, and removing obstacles.", binary: "100101" },
  { id: 22, name: "贲", pinyin: "Bì", meaning: "Grace", shortDesc: "Aesthetics, refinement, and inner vs outer beauty.", binary: "101001" },
  { id: 23, name: "剥", pinyin: "Bō", meaning: "Splitting Apart", shortDesc: "Decline, letting go, and survival through stillness.", binary: "000001" },
  { id: 24, name: "复", pinyin: "Fù", meaning: "Return", shortDesc: "Renewal of the light, fresh starts, and natural rhythm.", binary: "100000" },
  { id: 25, name: "无妄", pinyin: "Wú Wàng", meaning: "Innocence", shortDesc: "Acting without hidden motives, spontaneity, and truth.", binary: "100111" },
  { id: 26, name: "大畜", pinyin: "Dà Xù", meaning: "Great Taming", shortDesc: "Harnessing energy, accumulation of wisdom, and restraint.", binary: "111001" },
  { id: 27, name: "颐", pinyin: "Yí", meaning: "Nourishment", shortDesc: "Self-care, feeding the spirit, and right speech.", binary: "100001" },
  { id: 28, name: "大过", pinyin: "Dà Guò", meaning: "Great Preponderance", shortDesc: "Extraordinary burden, critical times, and bold action.", binary: "011110" },
  { id: 29, name: "坎", pinyin: "Kǎn", meaning: "The Abysmal Water", shortDesc: "Deep emotion, navigating danger, and inner sincerity.", binary: "010010" },
  { id: 30, name: "离", pinyin: "Lí", meaning: "The Clinging Fire", shortDesc: "Brightness, clarity, and dependence on light.", binary: "101101" },
  { id: 31, name: "咸", pinyin: "Xián", meaning: "Influence", shortDesc: "Mutual attraction, courtship, and heart connection.", binary: "001110" },
  { id: 32, name: "恒", pinyin: "Héng", meaning: "Duration", shortDesc: "Constancy, long-term commitment, and steady path.", binary: "011100" },
  { id: 33, name: "遁", pinyin: "Dùn", meaning: "Retreat", shortDesc: "Strategic withdrawal, saving energy, and avoiding ego.", binary: "001111" },
  { id: 34, name: "大壮", pinyin: "Dà Zhuàng", meaning: "Great Power", shortDesc: "Moral strength, restraint in power, and noble path.", binary: "111100" },
  { id: 35, name: "晋", pinyin: "Jìn", meaning: "Progress", shortDesc: "Advancing into the light, recognition, and rapid growth.", binary: "000101" },
  { id: 36, name: "明夷", pinyin: "Míng Yí", meaning: "Darkening of the Light", shortDesc: "Hiding brilliance, endurance in adversity, and resilience.", binary: "101000" },
  { id: 37, name: "家人", pinyin: "Jiā Rén", meaning: "The Family", shortDesc: "Order in the home, core values, and mutual support.", binary: "101011" },
  { id: 38, name: "睽", pinyin: "Kuí", meaning: "Opposition", shortDesc: "Diverse perspectives, unique paths, and creative tension.", binary: "110101" },
  { id: 39, name: "蹇", pinyin: "Jiǎn", meaning: "Obstruction", shortDesc: "Temporary blockages, turning inward, and patience.", binary: "001010" },
  { id: 40, name: "解", pinyin: "Xiè", meaning: "Deliverance", shortDesc: "Release of tension, forgiveness, and moving forward.", binary: "010100" },
  { id: 41, name: "损", pinyin: "Sǔn", meaning: "Decrease", shortDesc: "Simplification, letting go of excess, and sincerity.", binary: "110001" },
  { id: 42, name: "益", pinyin: "Yì", meaning: "Increase", shortDesc: "Abundance, self-improvement, and helping others.", binary: "100011" },
  { id: 43, name: "夬", pinyin: "Guài", meaning: "Break-through", shortDesc: "Decisiveness, resoluteness, and clearing the old.", binary: "111110" },
  { id: 44, name: "姤", pinyin: "Gòu", meaning: "Coming to Meet", shortDesc: "Sudden encounters, temptation, and unexpected bonding.", binary: "011111" },
  { id: 45, name: "萃", pinyin: "Cuì", meaning: "Gathering Together", shortDesc: "Congregation, collective spirit, and spiritual unity.", binary: "000110" },
  { id: 46, name: "升", pinyin: "Shēng", meaning: "Pushing Upward", shortDesc: "Gradual success, effort rewarded, and rising high.", binary: "011000" },
  { id: 47, name: "困", pinyin: "Kùn", meaning: "Oppression", shortDesc: "Exhaustion, confinement, and finding inner strength.", binary: "010110" },
  { id: 48, name: "井", pinyin: "Jǐng", meaning: "The Well", shortDesc: "Unchanging source, community nourishment, and depth.", binary: "011010" },
  { id: 49, name: "革", pinyin: "Gé", meaning: "Revolution", shortDesc: "Radical change, molting, and timing the shift.", binary: "101110" },
  { id: 50, name: "鼎", pinyin: "Dǐng", meaning: "The Caldron", shortDesc: "Transformation, spiritual food, and new structures.", binary: "011101" },
  { id: 51, name: "震", pinyin: "Zhèn", meaning: "The Arousing Thunder", shortDesc: "Sudden shock, awakening, and dynamic movement.", binary: "100100" },
  { id: 52, name: "艮", pinyin: "Gèn", meaning: "Keeping Still", shortDesc: "Mountains, meditation, and tranquility in action.", binary: "001001" },
  { id: 53, name: "渐", pinyin: "Jiàn", meaning: "Development", shortDesc: "Gradual progress, steady growth, and slow success.", binary: "001011" },
  { id: 54, name: "归妹", pinyin: "Guī Mèi", meaning: "The Marrying Maiden", shortDesc: "Impetuous action, complex relationships, and caution.", binary: "110100" },
  { id: 55, name: "丰", pinyin: "Fēng", meaning: "Abundance", shortDesc: "Fullness, zenith of success, and transient glory.", binary: "101100" },
  { id: 56, name: "旅", pinyin: "Lǚ", meaning: "The Wanderer", shortDesc: "Traveling, loneliness, and finding home in the soul.", binary: "001101" },
  { id: 57, name: "巽", pinyin: "Xùn", meaning: "The Gentle Wind", shortDesc: "Penetrating influence, flexibility, and persistence.", binary: "011011" },
  { id: 58, name: "兑", pinyin: "Duì", meaning: "The Joyous Lake", shortDesc: "Happiness, open communication, and shared delight.", binary: "110110" },
  { id: 59, name: "涣", pinyin: "Huàn", meaning: "Dispersion", shortDesc: "Dissolving ego, spiritual expansion, and unity.", binary: "010011" },
  { id: 60, name: "节", pinyin: "Jié", meaning: "Limitation", shortDesc: "Establishing boundaries, self-discipline, and rhythm.", binary: "110010" },
  { id: 61, name: "中孚", pinyin: "Zhōng Fú", meaning: "Inner Truth", shortDesc: "Sincerity, invisible connections, and deep empathy.", binary: "110011" },
  { id: 62, name: "小过", pinyin: "Xiǎo Guò", meaning: "Small Preponderance", shortDesc: "Small things matter, humility, and staying low.", binary: "001100" },
  { id: 63, name: "既济", pinyin: "Jì Jì", meaning: "After Completion", shortDesc: "Balance achieved, maintenance, and keeping order.", binary: "101010" },
  { id: 64, name: "未济", pinyin: "Wèi Jì", meaning: "Before Completion", shortDesc: "Infinite potential, the cycle restarts, hope.", binary: "010101" }
];
